'use strict';
// All data is synthetic. This file intentionally has no network or persistence API.
const $ = s => document.querySelector(s);
const events = [
 {name:'外卖员 01',relation:'外卖',time:'14:32',kind:'门前停留',status:'已确认',duration:'8 秒'},
 {name:'待确认人物',relation:'尚未分类',time:'11:08',kind:'门前经过',status:'待确认',duration:'6 秒'},
 {name:'朋友 01',relation:'朋友',time:'09:45',kind:'门前停留',status:'已确认',duration:'12 秒'},
 {name:'家人 01',relation:'家人',time:'08:16',kind:'门前经过',status:'已确认',duration:'5 秒'}
];
const categories = [['我','我',1],['家人','家',2],['朋友','友',2],['外卖','外',1],['快递','快',1],['访客','访',1],['其他','其',1]];
let selected = 0, filter = 'all', viewState = 'normal', toastTimer, opener;
const arrow = '<svg class="arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg>';
const scene = `<div class="scene"><svg viewBox="0 0 320 180" aria-hidden="true"><path d="M0 148h320M20 148V22h105v126M33 148V36h78v112M98 85v7M145 148V64h132v84M156 78h107M156 105h107M156 132h107"/><circle cx="225" cy="64" r="12"/><path d="M203 119V97a22 22 0 0 1 44 0v22M211 119v28M239 119v28"/></svg><span class="scene-label">示意画面 · 不是真实录像</span><button class="scene-play" data-demo="原型不加载录像；正式页面继续使用受保护媒体播放">预览说明</button></div>`;
function notify(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function showDialog(title,html,source){opener=source||document.activeElement;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#detail').showModal();$('#close').focus();}
function details(i){const e=events[i];return `${scene}<div class="detail-summary"><div><h2>${e.name}</h2><p class="subtle">示例日 ${e.time} · 北京时间</p></div><span class="badge ${e.status==='待确认'?'pending':''}">${e.status}</span></div><dl class="facts"><div class="fact"><dt>事件类型</dt><dd>${e.kind}</dd></div><div class="fact"><dt>与您家的关系</dt><dd>${e.relation}</dd></div><div class="fact"><dt>录像时长</dt><dd>${e.duration}</dd></div><div class="fact"><dt>处理结果</dt><dd>已完成分析</dd></div></dl><div class="actions"><button class="primary" data-review="${i}">${e.status==='待确认'?'核对这个人物':'核对人物信息'}</button><button class="quiet" data-demo="示例已重新分析，真实记录未改变">重新分析</button></div><p class="quiet-note">人工修正可追溯、可撤销；识别结果不会控制门锁。</p>`;}
function renderEvents(){const visible=events.map((e,i)=>({...e,i})).filter(e=>filter==='all'||e.status==='待确认');$('#content').innerHTML=`<div class="toolbar"><div class="segmented" aria-label="事件筛选"><button data-filter="all" aria-pressed="${filter==='all'}">全部事件</button><button data-filter="pending" aria-pressed="${filter==='pending'}">待确认 <span>1</span></button></div><span class="countline">示例日 · ${visible.length} 条记录 · 北京时间</span></div><div class="events-grid"><section class="panel"><div class="section-top"><h2>示例日</h2><small>仅用于设计预览</small></div>${visible.map(e=>`<button class="event-row" data-event="${e.i}" aria-pressed="${selected===e.i}"><span class="avatar" aria-hidden="true">${e.status==='待确认'?'？':e.relation[0]}</span><span><strong>${e.name}</strong><small>${e.kind} · ${e.status}</small></span><span class="time">${e.time}</span></button>`).join('')}</section><section class="panel desktop-detail"><div class="section-top"><h2>事件详情</h2><small>对应所选记录</small></div><div class="detail-body">${details(selected)}</div></section></div>`;}
function renderPeople(){$('#content').innerHTML=`<div class="people-layout"><section class="pending-entry"><div><span class="badge pending">待确认 · 2 组示例</span><h2 style="margin-top:12px">先看看还不认识的人</h2><p>未知人物不预分类。核对样本和对应录像后，再确认身份。</p></div><button class="primary" id="pending">核对待确认人物</button></section><section><div class="toolbar"><h2>已确认人物</h2><span class="countline">按类别聚合 · 每类一个入口</span></div><div class="category-grid">${categories.map(([label,mark,count],i)=>`<button class="category" data-category="${i}"><span class="avatar" aria-hidden="true">${mark}</span><span><strong>${label}</strong><small>${count} 位示例人物</small></span>${arrow}</button>`).join('')}</div></section><p class="quiet-note">代表样本将持续积累。这里仅使用字母与文字占位，不展示真实人脸。</p></div>`;}
function renderOperations(){$('#content').innerHTML=`<section class="panel grouped"><div class="section-top"><h2>系统状态</h2><span class="badge">示例正常</span></div>${[['录像下载','最近一次示例任务已完成','已下载'],['人物分析','没有待处理的示例录像','正常'],['备份回执','尚未收到示例回执，不代表已完成备份','待核对']].map(([t,d,s])=>`<div class="operation-row"><div><strong>${t}</strong><p>${d}</p></div><span class="${s==='待核对'?'':'healthy'}">${s}</span></div>`).join('')}</section><section class="panel grouped"><div class="section-top"><h2>下载器回报</h2><small>北京时间 · 合成示例</small></div><div class="table-wrap"><table><thead><tr><th scope="col">示例时间</th><th scope="col">状态</th><th scope="col">说明</th></tr></thead><tbody><tr><td>14:34</td><td class="healthy">已下载</td><td>录像已保存</td></tr><tr><td>14:33</td><td>正在重试</td><td>录像片段获取失败</td></tr></tbody></table></div></section><section class="panel"><div class="section-top"><h2>人工操作</h2><small>可核对，可撤销</small></div><div class="operation-row"><div><strong>确认人物为朋友 01</strong><p>示例操作 · 未改变真实记录</p></div><button class="quiet" data-demo="已模拟撤销；没有真实数据变更">撤销示例</button></div></section>`;}
function renderSettings(){$('#content').innerHTML=`<section class="panel grouped"><div class="section-top"><h2>通知</h2><small>仅修改预览状态</small></div>${[['identity','人物身份通知','训练期间关闭，确认稳定后再开启。',false],['risk','风险提醒','未开启。识别结果不会触发开锁。',false],['failure','运行故障通知','及时了解下载或分析异常。',true]].map(([id,t,d,on])=>`<div class="settings-row"><div><h3>${t}</h3><p id="${id}-hint">${d}</p></div><label class="switch-hit"><input class="switch" type="checkbox" aria-label="${t}" aria-describedby="${id}-hint" ${on?'checked':''} data-toggle></label></div>`).join('')}</section><section class="panel grouped"><div class="section-top"><h2>登录会话</h2></div><div class="settings-row"><div><h3>退出观察簿</h3><p>正式页面会撤销当前会话；这里仅返回登录预览。</p></div><button class="quiet" id="logout">退出预览</button></div></section><p class="quiet-note">下载延迟、保留与认证仍由原有服务管理。本设计不修改任何运行配置。</p>`;}
function render(){const route=['events','people','operations','settings','login'].includes(location.hash.slice(1))?location.hash.slice(1):'events';$('#login').hidden=route!=='login';$('#shell').hidden=route==='login';if(route==='login')return;document.querySelectorAll('nav a').forEach(a=>{if(a.dataset.route===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const info={events:['门口发生了什么','按北京时间查看记录，点开一条了解详情。','事件'],people:['认识门前的人','按类别查看已确认人物，单独核对未知人物。','人物'],operations:['运行情况','下载、分析和备份是否完成，分别核对。','运行'],settings:['按您的习惯设置','保持通知克制，让人工确认始终可控。','设置']}[route];$('#title').textContent=info[0];$('#subtitle').textContent=info[1];$('#crumb').textContent=info[2];$('#feedback').textContent='';if(route==='events')renderEvents();if(route==='people')renderPeople();if(route==='operations')renderOperations();if(route==='settings')renderSettings();$('#content').insertAdjacentHTML('beforeend','<div class="preview-controls" style="margin-top:28px"><label for="demo-state">预览反馈状态</label><select id="demo-state"><option value="normal">正常示例</option><option value="empty">空状态</option><option value="loading">加载状态</option><option value="error">错误状态</option></select><small>只影响当前设计预览</small></div>');$('#demo-state').value='normal';viewState='normal';}
window.addEventListener('hashchange',()=>{if(location.hash==='#main'){$('#main').focus();return;}if($('#detail').open)$('#detail').close();$('#feedback').removeAttribute('aria-busy');render();if(location.hash!=='#login')$('#title').focus();});
$('#close').addEventListener('click',()=>$('#detail').close());
$('#detail').addEventListener('close',()=>{if(opener?.isConnected)opener.focus();});
$('#enter').addEventListener('click',()=>location.hash='events');
$('#refresh').addEventListener('click',()=>{render();notify('示例已刷新，没有访问真实服务');});
document.addEventListener('change',e=>{if(e.target.matches('[data-toggle]'))notify('仅改变预览开关，没有保存运行配置');if(e.target.id==='demo-state'){viewState=e.target.value;const feedback=$('#feedback');if(viewState==='normal')render();if(viewState==='loading'){feedback.textContent='正在整理示例记录… 页面保持可操作。';feedback.setAttribute('aria-busy','true');}else feedback.removeAttribute('aria-busy');if(viewState==='error')feedback.innerHTML='<span class="error">暂时无法读取记录。请稍后重试。</span> <button class="quiet" id="restore">恢复示例</button>';if(viewState==='empty'){$('#content').innerHTML='<section class="panel empty"><h2>还没有可查看的记录</h2><p>真实下载器写入第一段录像后，会自动出现在这里。本页仅为合成预览。</p><button class="primary" id="restore">恢复示例</button></section>';}}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){filter=b.dataset.filter;selected=filter==='pending'?1:0;renderEvents();}if(b.dataset.event!==undefined){selected=Number(b.dataset.event);if(matchMedia('(max-width:1100px)').matches)showDialog('事件详情',details(selected),b);else{renderEvents();$(`[data-event="${selected}"]`).focus();}}if(b.dataset.demo)notify(b.dataset.demo);if(b.id==='restore')render();if(b.id==='logout')location.hash='login';if(b.dataset.category!==undefined){const [label,,count]=categories[Number(b.dataset.category)];showDialog(`${label} · ${count} 位示例人物`,`${Array.from({length:count},(_,i)=>`<div class="person-row"><span class="avatar" aria-hidden="true">${label[0]}</span><div><strong>${label} ${String(i+1).padStart(2,'0')}</strong><small style="display:block">合成示例 · 代表样本占位</small></div><button class="quiet" data-demo="正式页面保留修改与合并；此处仅展示设计">查看信息</button></div>`).join('')}<p class="quiet-note">每个类别入口聚合展示，展开后仍可逐人管理。</p>`,b);}if(b.id==='pending')showDialog('待确认人物 · 2 组示例',[1,2].map(i=>`<section class="review-card"><h3>待确认人物 ${i}</h3><p>清晰样本与对应录像一起核对，不推断类别。</p><div class="sample"><span class="avatar large" aria-hidden="true">？</span><span>合成样本占位<br><small>不是真实人脸</small></span></div><div class="actions"><button class="primary" data-review="1">确认并命名</button><button class="quiet" data-demo="仅演示入口；正式页面保留并入已确认人物能力">并入已确认人物</button><button class="quiet" data-demo="已模拟误检标记，没有修改真实记录">标记为误检</button></div></section>`).join(''),b);if(b.dataset.review!==undefined){if($('#detail').open){$('#dialog-title').textContent='核对人物 · 模拟操作';$('#dialog-body').innerHTML='<p>本原型不保存身份信息。正式页面保留命名、关系选择与可撤销审计。</p><label for="relation" style="display:block;margin:20px 0 8px">与您家的关系</label><select id="relation" style="padding:12px;border-radius:10px;width:100%">'+categories.map(([label])=>`<option>${label}</option>`).join('')+'</select><div class="actions"><button class="primary" data-demo="模拟确认完成，真实人物未修改">模拟确认</button></div>';$('#relation').focus();}else showDialog('核对人物 · 模拟操作','<p>这里不保存人物信息。正式页面继续使用现有命名与关系选择功能。</p><div class="actions"><button class="primary" data-demo="模拟确认完成，真实人物未修改">模拟确认</button></div>',b);}});
render();
