const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const source = fs.readFileSync(require("node:path").join(__dirname, "../src/doorlock_sentinel/static/app.js"), "utf8");
function setup() {
  const nodes = new Map();
  const node = () => ({innerHTML:"", hidden:true, open:false, options:[], value:"", textContent:"", setAttribute(){}, focus(){}, close(){this.open=false;}, showModal(){this.open=true;}, querySelector(){return null;}});
  const scope = {document:{querySelector(s){if(s === "#modal-relationship" || s === "#modal-name-hint") return null; if(!nodes.has(s)) nodes.set(s,node()); return nodes.get(s);}}, location:{hash:"#people"}, setTimeout(){}, crypto:{randomUUID:()=>"synthetic-key"}, DoorlockTime:{dayLabel:()=>"",formatDate:()=>""}};
  vm.createContext(scope);
  vm.runInContext(source.slice(0,source.indexOf('document.addEventListener("click"')),scope);
  const run = code => vm.runInContext(code,scope);
  run('state.csrf="synthetic";state.route="people";state.people=[{id:"cleaner",display_name:"保洁1"},{id:"neighbor",display_name:"邻居1"}];state.clusters=[{id:"c1",tracks:[]},{id:"c2",tracks:[]}];');
  return {nodes,run};
}
test("manual open and closed choices survive refresh and leaving people", async () => {
  const {nodes,run}=setup();
  run('renderPeopleContent();renderPeople=async()=>renderPeopleContent();setHeader=()=>{};');
  const pending=run('$(".pending-disclosure")');
  pending.open=true;
  await run('loadRoute()');
  assert.ok(nodes.get("#content").innerHTML.includes('class="pending-disclosure" open'));
  pending.open=false;
  await run('loadRoute()');
  assert.ok(!nodes.get("#content").innerHTML.includes('class="pending-disclosure" open'));
  pending.open=true;
  run('location.hash="#events";renderEvents=async()=>{};');
  await run('loadRoute()');
  assert.equal(run('state.pendingOpen'),true);
});
test("successful merge remembers target; cancel and failure do not replace it", async () => {
  const {nodes,run}=setup();
  const select=run('$("#modal-target")');
  select.options=[{value:"person:cleaner"},{value:"person:neighbor"},{value:"cluster:c2"}];
  select.value="person:cleaner";
  run('mutate=async()=>{};mergeCluster("c1")');
  select.value="person:neighbor";
  await run('state.modalHandler()');
  assert.equal(run('state.lastMergeTarget'),"person:neighbor");
  select.value="person:cleaner";
  run('mergeCluster("c2")');
  assert.equal(select.value,"person:neighbor");
  select.value="person:cleaner"; // change then cancel, no submit
  run('modal.close();mergeCluster("c2")');
  assert.equal(select.value,"person:neighbor");
  select.value="person:cleaner";
  run('mutate=async()=>{throw new Error("synthetic conflict")};');
  await assert.rejects(run('state.modalHandler()'),/synthetic conflict/);
  assert.equal(run('state.lastMergeTarget'),"person:neighbor");
  run('mutate=async()=>{};mergeCluster("c1")');
  select.value="cluster:c2";
  await run('state.modalHandler()');
  assert.equal(run('state.lastMergeTarget'),"cluster:c2");
});
test("person dialogs share successful target memory; missing or excluded targets fall back", async () => {
  const {run}=setup();
  const select=run('$("#modal-target")');
  select.options=[{value:"cleaner"},{value:"neighbor"}]; select.value="cleaner";
  run('state.lastMergeTarget="person:neighbor";mergePerson("source")');
  assert.equal(select.value,"neighbor");
  run('mutate=async()=>{}');
  await run('state.modalHandler()');
  assert.equal(run('state.lastMergeTarget'),"person:neighbor");
  select.options=[{value:"cleaner"}];select.value="cleaner";
  run('mergePerson("neighbor")');
  assert.equal(select.value,"cleaner");
  run('state.lastMergeTarget="person:deleted";restoreMergeTarget("person:")');
  assert.equal(select.value,"cleaner");
});
test("logout or expiry resets preferences and expiry during refresh cannot restore target", async () => {
  const {run}=setup();
  const select=run('$("#modal-target")');
  select.options=[{value:"person:neighbor"}]; select.value="person:neighbor";
  run('state.pendingOpen=true;state.lastMergeTarget="person:neighbor";showLogin()');
  assert.equal(run('state.pendingOpen'),false);
  assert.equal(run('state.lastMergeTarget'),"");
  run('state.csrf="synthetic";mutate=async()=>showLogin();mergeCluster("c1")');
  await run('state.modalHandler()');
  assert.equal(run('state.lastMergeTarget'),"");
});
