"""initial durable schema

Revision ID: 0001
Revises:
Create Date: 2026-08-29 21:06:03.301313
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_manifest",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("artifact_type", sa.String(length=48), nullable=False),
        sa.Column("logical_path", sa.Text(), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("retention_class", sa.String(length=48), nullable=False),
        sa.Column("retention_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("backup_state", sa.String(length=24), nullable=False),
        sa.Column("backup_receipt_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("logical_path"),
    )
    op.create_index(
        "ix_artifact_backup", "artifact_manifest", ["backup_state", "retention_class"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_manifest_artifact_type"),
        "artifact_manifest",
        ["artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_manifest_backup_state"),
        "artifact_manifest",
        ["backup_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_manifest_retention_class"),
        "artifact_manifest",
        ["retention_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_manifest_retention_due_at"),
        "artifact_manifest",
        ["retention_due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifact_manifest_sha256"), "artifact_manifest", ["sha256"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_manifest_state"), "artifact_manifest", ["state"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=96), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_actor"), "audit_log", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_log_request_id"), "audit_log", ["request_id"], unique=False)
    op.create_index(op.f("ix_audit_log_subject_id"), "audit_log", ["subject_id"], unique=False)
    op.create_table(
        "download_reports",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_digest", sa.String(length=64), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=96), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_digest"),
    )
    op.create_index(
        op.f("ix_download_reports_event_time"), "download_reports", ["event_time"], unique=False
    )
    op.create_index(op.f("ix_download_reports_state"), "download_reports", ["state"], unique=False)
    op.create_table(
        "login_throttle",
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key_hash"),
    )
    op.create_index(
        op.f("ix_login_throttle_locked_until"), "login_throttle", ["locked_until"], unique=False
    )
    op.create_table(
        "manual_operations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=False),
        sa.Column("after_json", sa.JSON(), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undo_operation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["undo_operation_id"],
            ["manual_operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_manual_operations_operation"), "manual_operations", ["operation"], unique=False
    )
    op.create_index(
        op.f("ix_manual_operations_subject_id"), "manual_operations", ["subject_id"], unique=False
    )
    op.create_table(
        "model_registry",
        sa.Column("model_id", sa.String(length=96), nullable=False),
        sa.Column("detector_sha256", sa.String(length=64), nullable=False),
        sa.Column("recognizer_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("license_class", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=160), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        "ix_outbox_claim", "outbox_messages", ["state", "available_at", "priority"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_available_at"), "outbox_messages", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_lease_until"), "outbox_messages", ["lease_until"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_priority"), "outbox_messages", ["priority"], unique=False
    )
    op.create_index(op.f("ix_outbox_messages_state"), "outbox_messages", ["state"], unique=False)
    op.create_index(op.f("ix_outbox_messages_topic"), "outbox_messages", ["topic"], unique=False)
    op.create_table(
        "persons",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("relationship", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("merged_into_id", sa.String(length=64), nullable=True),
        sa.Column("matched_events", sa.Integer(), nullable=False),
        sa.Column("distinct_days", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_persons_merged_into_id"), "persons", ["merged_into_id"], unique=False)
    op.create_index(op.f("ix_persons_relationship"), "persons", ["relationship"], unique=False)
    op.create_index(op.f("ix_persons_status"), "persons", ["status"], unique=False)
    op.create_table(
        "runtime_settings",
        sa.Column("key", sa.String(length=96), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("updated_by", sa.String(length=128), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "video_ingest",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mtime_ns", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=96), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("failure_notified", sa.Boolean(), nullable=False),
        sa.Column("retry_requested", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=True),
        sa.Column("duplicate_of_id", sa.String(length=64), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_index(
        "ix_ingest_claim", "video_ingest", ["state", "available_at", "lease_until"], unique=False
    )
    op.create_index(
        op.f("ix_video_ingest_available_at"), "video_ingest", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_video_ingest_lease_until"), "video_ingest", ["lease_until"], unique=False
    )
    op.create_index(op.f("ix_video_ingest_sha256"), "video_ingest", ["sha256"], unique=False)
    op.create_index(op.f("ix_video_ingest_state"), "video_ingest", ["state"], unique=False)
    op.create_table(
        "web_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_web_sessions_expires_at"), "web_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_web_sessions_revoked_at"), "web_sessions", ["revoked_at"], unique=False
    )
    op.create_index(op.f("ix_web_sessions_token_hash"), "web_sessions", ["token_hash"], unique=True)
    op.create_table(
        "backup_receipts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("remote_sha256", sa.String(length=64), nullable=True),
        sa.Column("remote_size_bytes", sa.Integer(), nullable=True),
        sa.Column("remote_locator", sa.Text(), nullable=True),
        sa.Column("receipt_source", sa.String(length=64), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifact_manifest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backup_receipts_artifact_id"), "backup_receipts", ["artifact_id"], unique=True
    )
    op.create_index(op.f("ix_backup_receipts_state"), "backup_receipts", ["state"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("video_ingest_id", sa.String(length=64), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("external_event_id", sa.String(length=160), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("unlock_method", sa.String(length=96), nullable=True),
        sa.Column("operation_user", sa.String(length=96), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("analysis_state", sa.String(length=24), nullable=False),
        sa.Column("track_count", sa.Integer(), nullable=False),
        sa.Column("skipped_face_count", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("risk_reasons", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["artifact_manifest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_ingest_id"],
            ["video_ingest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_artifact_id"),
        sa.UniqueConstraint("video_ingest_id"),
    )
    op.create_index(op.f("ix_events_analysis_state"), "events", ["analysis_state"], unique=False)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(
        op.f("ix_events_external_event_id"), "events", ["external_event_id"], unique=False
    )
    op.create_index(op.f("ix_events_occurred_at"), "events", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_events_risk_score"), "events", ["risk_score"], unique=False)
    op.create_index("ix_events_timeline", "events", ["occurred_at", "analysis_state"], unique=False)
    op.create_table(
        "person_index",
        sa.Column("person_id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=96), nullable=False),
        sa.Column("centroid", sa.LargeBinary(), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("prototype_count", sa.Integer(), nullable=False),
        sa.Column("search_prototype_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("person_id", "model_id"),
    )
    op.create_table(
        "unknown_clusters",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=96), nullable=False),
        sa.Column("centroid", sa.LargeBinary(), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("distinct_days", sa.Integer(), nullable=False),
        sa.Column("high_quality_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("labeled_person_id", sa.String(length=64), nullable=True),
        sa.Column("merged_into_id", sa.String(length=64), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("review_not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["labeled_person_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["unknown_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unknown_clusters_model_id"), "unknown_clusters", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_unknown_clusters_status"), "unknown_clusters", ["status"], unique=False
    )
    op.create_table(
        "analysis_skips",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=96), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=True),
        sa.Column("detector_score", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_skips_event_id"), "analysis_skips", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_skips_reason"), "analysis_skips", ["reason"], unique=False)
    op.create_table(
        "face_tracks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("track_index", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=96), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("representative", sa.Boolean(), nullable=False),
        sa.Column("first_timestamp", sa.Float(), nullable=False),
        sa.Column("last_timestamp", sa.Float(), nullable=False),
        sa.Column("best_bbox_json", sa.JSON(), nullable=False),
        sa.Column("best_face_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("best_frame_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("decision_reason", sa.String(length=160), nullable=True),
        sa.Column("person_id", sa.String(length=64), nullable=True),
        sa.Column("unknown_cluster_id", sa.String(length=64), nullable=True),
        sa.Column("top_similarity", sa.Float(), nullable=True),
        sa.Column("second_similarity", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["best_face_artifact_id"],
            ["artifact_manifest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["best_frame_artifact_id"],
            ["artifact_manifest.id"],
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unknown_cluster_id"],
            ["unknown_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "track_index"),
    )
    op.create_index(op.f("ix_face_tracks_decision"), "face_tracks", ["decision"], unique=False)
    op.create_index(op.f("ix_face_tracks_event_id"), "face_tracks", ["event_id"], unique=False)
    op.create_index(op.f("ix_face_tracks_model_id"), "face_tracks", ["model_id"], unique=False)
    op.create_index(op.f("ix_face_tracks_person_id"), "face_tracks", ["person_id"], unique=False)
    op.create_index(
        op.f("ix_face_tracks_representative"), "face_tracks", ["representative"], unique=False
    )
    op.create_index(
        op.f("ix_face_tracks_unknown_cluster_id"),
        "face_tracks",
        ["unknown_cluster_id"],
        unique=False,
    )
    op.create_table(
        "cannot_links",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("left_track_id", sa.String(length=64), nullable=False),
        sa.Column("right_track_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_track_id"],
            ["face_tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_track_id"],
            ["face_tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("left_track_id", "right_track_id"),
    )
    op.create_index(
        op.f("ix_cannot_links_left_track_id"), "cannot_links", ["left_track_id"], unique=False
    )
    op.create_index(
        op.f("ix_cannot_links_right_track_id"), "cannot_links", ["right_track_id"], unique=False
    )
    op.create_table(
        "face_prototypes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("person_id", sa.String(length=64), nullable=False),
        sa.Column("source_track_id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=96), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("search_enabled", sa.Boolean(), nullable=False),
        sa.Column("admitted_reason", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_track_id"],
            ["face_tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "source_track_id"),
    )
    op.create_index(
        op.f("ix_face_prototypes_model_id"), "face_prototypes", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_face_prototypes_person_id"), "face_prototypes", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_face_prototypes_search_enabled"),
        "face_prototypes",
        ["search_enabled"],
        unique=False,
    )
    op.create_table(
        "person_observations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("person_id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_day", sa.String(length=10), nullable=False),
        sa.Column("source_track_id", sa.String(length=64), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_track_id"],
            ["face_tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "event_id"),
    )
    op.create_index(
        op.f("ix_person_observations_event_day"), "person_observations", ["event_day"], unique=False
    )
    op.create_index(
        op.f("ix_person_observations_event_id"), "person_observations", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_person_observations_person_id"), "person_observations", ["person_id"], unique=False
    )
    op.create_table(
        "unknown_cluster_members",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("cluster_id", sa.String(length=64), nullable=False),
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_day", sa.String(length=10), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["unknown_clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(["track_id"], ["face_tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id"),
    )
    op.create_index(
        op.f("ix_unknown_cluster_members_cluster_id"),
        "unknown_cluster_members",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unknown_cluster_members_event_day"),
        "unknown_cluster_members",
        ["event_day"],
        unique=False,
    )
    op.create_index(
        op.f("ix_unknown_cluster_members_event_id"),
        "unknown_cluster_members",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unknown_cluster_members_event_id"), table_name="unknown_cluster_members")
    op.drop_index(
        op.f("ix_unknown_cluster_members_event_day"), table_name="unknown_cluster_members"
    )
    op.drop_index(
        op.f("ix_unknown_cluster_members_cluster_id"), table_name="unknown_cluster_members"
    )
    op.drop_table("unknown_cluster_members")
    op.drop_index(op.f("ix_person_observations_person_id"), table_name="person_observations")
    op.drop_index(op.f("ix_person_observations_event_id"), table_name="person_observations")
    op.drop_index(op.f("ix_person_observations_event_day"), table_name="person_observations")
    op.drop_table("person_observations")
    op.drop_index(op.f("ix_face_prototypes_search_enabled"), table_name="face_prototypes")
    op.drop_index(op.f("ix_face_prototypes_person_id"), table_name="face_prototypes")
    op.drop_index(op.f("ix_face_prototypes_model_id"), table_name="face_prototypes")
    op.drop_table("face_prototypes")
    op.drop_index(op.f("ix_cannot_links_right_track_id"), table_name="cannot_links")
    op.drop_index(op.f("ix_cannot_links_left_track_id"), table_name="cannot_links")
    op.drop_table("cannot_links")
    op.drop_index(op.f("ix_face_tracks_unknown_cluster_id"), table_name="face_tracks")
    op.drop_index(op.f("ix_face_tracks_representative"), table_name="face_tracks")
    op.drop_index(op.f("ix_face_tracks_person_id"), table_name="face_tracks")
    op.drop_index(op.f("ix_face_tracks_model_id"), table_name="face_tracks")
    op.drop_index(op.f("ix_face_tracks_event_id"), table_name="face_tracks")
    op.drop_index(op.f("ix_face_tracks_decision"), table_name="face_tracks")
    op.drop_table("face_tracks")
    op.drop_index(op.f("ix_analysis_skips_reason"), table_name="analysis_skips")
    op.drop_index(op.f("ix_analysis_skips_event_id"), table_name="analysis_skips")
    op.drop_table("analysis_skips")
    op.drop_index(op.f("ix_unknown_clusters_status"), table_name="unknown_clusters")
    op.drop_index(op.f("ix_unknown_clusters_model_id"), table_name="unknown_clusters")
    op.drop_table("unknown_clusters")
    op.drop_table("person_index")
    op.drop_index("ix_events_timeline", table_name="events")
    op.drop_index(op.f("ix_events_risk_score"), table_name="events")
    op.drop_index(op.f("ix_events_occurred_at"), table_name="events")
    op.drop_index(op.f("ix_events_external_event_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_analysis_state"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_backup_receipts_state"), table_name="backup_receipts")
    op.drop_index(op.f("ix_backup_receipts_artifact_id"), table_name="backup_receipts")
    op.drop_table("backup_receipts")
    op.drop_index(op.f("ix_web_sessions_token_hash"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_revoked_at"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_expires_at"), table_name="web_sessions")
    op.drop_table("web_sessions")
    op.drop_index(op.f("ix_video_ingest_state"), table_name="video_ingest")
    op.drop_index(op.f("ix_video_ingest_sha256"), table_name="video_ingest")
    op.drop_index(op.f("ix_video_ingest_lease_until"), table_name="video_ingest")
    op.drop_index(op.f("ix_video_ingest_available_at"), table_name="video_ingest")
    op.drop_index("ix_ingest_claim", table_name="video_ingest")
    op.drop_table("video_ingest")
    op.drop_table("runtime_settings")
    op.drop_index(op.f("ix_persons_status"), table_name="persons")
    op.drop_index(op.f("ix_persons_relationship"), table_name="persons")
    op.drop_index(op.f("ix_persons_merged_into_id"), table_name="persons")
    op.drop_table("persons")
    op.drop_index(op.f("ix_outbox_messages_topic"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_state"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_priority"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_lease_until"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_available_at"), table_name="outbox_messages")
    op.drop_index("ix_outbox_claim", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_table("model_registry")
    op.drop_index(op.f("ix_manual_operations_subject_id"), table_name="manual_operations")
    op.drop_index(op.f("ix_manual_operations_operation"), table_name="manual_operations")
    op.drop_table("manual_operations")
    op.drop_index(op.f("ix_login_throttle_locked_until"), table_name="login_throttle")
    op.drop_table("login_throttle")
    op.drop_index(op.f("ix_download_reports_state"), table_name="download_reports")
    op.drop_index(op.f("ix_download_reports_event_time"), table_name="download_reports")
    op.drop_table("download_reports")
    op.drop_index(op.f("ix_audit_log_subject_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_request_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_artifact_manifest_state"), table_name="artifact_manifest")
    op.drop_index(op.f("ix_artifact_manifest_sha256"), table_name="artifact_manifest")
    op.drop_index(op.f("ix_artifact_manifest_retention_due_at"), table_name="artifact_manifest")
    op.drop_index(op.f("ix_artifact_manifest_retention_class"), table_name="artifact_manifest")
    op.drop_index(op.f("ix_artifact_manifest_backup_state"), table_name="artifact_manifest")
    op.drop_index(op.f("ix_artifact_manifest_artifact_type"), table_name="artifact_manifest")
    op.drop_index("ix_artifact_backup", table_name="artifact_manifest")
    op.drop_table("artifact_manifest")
    # ### end Alembic commands ###
